Update jenkinfile2

diff --git a/jenkinfile2 b/jenkinfile2
--- a/jenkinfile2
+++ b/jenkinfile2
@@ -17,9 +17,9 @@ pipeline {
             steps {
                 echo 'Running Docker container...'
                 sh '''
-                    docker stop my-web-app || true
-                    docker rm my-web-app || true
-                    docker run -d --name my-web-app -p 8080:80 my-web-app
+                docker stop my-web-app || true
+                docker rm my-web-app || true
+                docker run -d --name my-web-app -p 8090:80 my-web-app
                 '''
             }
         }
@@ -32,7 +32,7 @@ pipeline {
             echo 'Application deployed successfully!'
         }
         failure {
-            echo 'Pipeline failed.'
+            echo 'Pipeline failed!'
         }
     }
 }
